#------------------------
# Header config
title: Chia Yu's Blog
author: Chia Yu
# put the logo on the ${blog_path}/source/img/${picname}.png or use urls
logo_img: https://blog.iddle.dev/public/images/icon.png
author_img: https://blog.iddle.dev/public/images/avatar.jpg
author_description: What if we just hadn't said goodbye?
#------------------------
# Navbar config
#------------------------
menus:
  home: /
  archive: /archives
  tags: /tags
  categories: /categories
  about: /about
  friends: /links
  # artitalk: /shuoshuo # You can uncomment to add this route

about:
  description: description
  social_links:
    - { icon: icon-github, link: https://github.com/kk98033 }
    - { icon: icon-steam, link: https://steamcommunity.com/id/IddleFromTaiwan/ }
    - { icon: icon-youtube, link: https://www.youtube.com/channel/UCubeo2tni91PwEGC22a11Kg }

#------------------------
# Links
#------------------------
links:
  name: 
    name: iddle.dev
    url: https://iddle.dev
    avatar: https://blog.iddle.dev/public/images/avatar.jpg
    description: 我的主網站
  # name:
  #   url: https://example.com
  #   avatar:
  #   description:
  #------------------------
  # tip: if you want to use QQ avatar without giving away your QQ number,
  # you can use this api to get an encrypted url:
  # https://ptlogin2.qq.com/getface?appid=1006102&imgtype=3&uin=${yourQQNumber}
  # and use the encrypted url in the json
  #------------------------

#------------------------
# Post
#------------------------
toc:
  showListNumber: false
  maxDepth: 6
  minDepth: 1

copyright:
  enable: true
  writer: # if writer is empty we will use config.author as writer
  declare: 本網站所有文章除特別聲明外，均採用<a target="_blank" rel="noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh">CC BY-NC-SA 4.0 協議</a>。轉載請註明出處！
  style: warning # the style uses note warning | danger | primary | info | success

search:
  enable: true
  path: https://blog.iddle.dev/public/search.json
  field: posts
  searchContent: false

og:
  enable: true
  title: true
  url: true
  image: true
  description: true
  article: true
#------------------------
# Footer
#------------------------
footer:
  copyYear: 2023
  # if showPoweredBy is ture, 'Powered by Hexo' will be seen on the footer
  showPoweredBy: true
  # if showThemeName is ture, 'Theme - Kaze' will be seen on the footer
  showThemeName: true
  #------------------------
  # Record config
  # please put the gov image in ${yoursite}/img/beian.png
  RecordInfo: "" # your Record info such as '某ICP备xxx号'
  govRecordInfo: "" # your gov record info such as '某公网安备xxx号'
  govRecordUrl: "" # your gov record url
  #------------------------
  # pv / uv statistics config
  #------------------------
  statistics:
    enable: true
    type: busuanzi # now version only supports busuanzi
    pv:
      enable: false
      style: 本網站總訪問數{}次 # the style will be shown as $1{pv}$2
    uv:
      enable: true
      style: 本網站總訪客數{}次 # the style will be shown as $1{uv}$2

widgets:
  showWidgetsMobiles: "none"
#------------------------
# animation config
#------------------------
# if scrollUpAnimation is true, there will be scroll-up animation.
scrollUpAnimation: true

#------------------------
# comment config
#------------------------
comment:
  enable: true
  type: waline # valine | gitalk | livere | disqus | we recommend valine | waline
  # gitalk config details can see in https://github.com/gitalk/gitalk/blob/master/readme-cn.md
  # waline config details can see in https://waline.js.org
  valine:
    appId: FlvVFFfqv9u6gMMUInIWjG1N-MdYXbMMI
    appKey: cxHVy5zMwaSjZiUpXDwkPr7x
    placeholder: Write down your comment
    path: window.location.pathname
    avatar: monsterid
    meta: ["nick", "mail"] # "link"
    pageSize: 10
    visitor: true
    highlight: true
    recordIP: true
    serverURLs: https://blog.iddle.dev # leancloud国内自定义域名
    emojiCDN: https://emojicdn.elk.sh/
    emojiMaps: null
    enableQQ: false
    requiredFields: []
  gitalk:
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.href
    distractionFreeMode: false
    # en | zh-CN | zh-TW
    language: en # navigator.language || navigator.userLanguage || zh-TW || en
    labels: ['Gitalk']
    perPage: 10
  livere:
    uid:
  waline:
    serverURL: https://waline-comment-test-jczd1s1z3-kk98033.vercel.app/
    path: window.location.pathname
    avatar: https://blog.iddle.dev/public/images/avatar.jpg
    meta: ["nick", "mail"]
    requiredMeta: []
    emoji: [
      'https://unpkg.com/@waline/emojis@1.1.0/alus',
      'https://unpkg.com/@waline/emojis@1.1.0/bmoji',
      '//unpkg.com/@waline/emojis@1.1.0/bilibili',
      'https://unpkg.com/@waline/emojis@1.1.0/tw-symbol',
    ]
    # email settings
    # SMTP_SERVICE: Gmail
    # SMTP_USER: mlp98033@gmail.com
    # SMTP_PASS: vhegotpeuvacpwbb
    # SMTP_SECURE: true
    # SITE_NAME: Chia Yu's Blog
    # SITE_URL: https://blog.iddle.dev/
    # SENDER_NAME: Marisa
    # AUTHOR_EMAIL: a8829037@gmail.com

    lang: en
    dark: auto # html[data-user-color-scheme="dark"]
    login: disabled
    wordLimit: 0
    pageSize: 10
    locale:
      placeholder: 如果要收到評論回覆通知，請務必填上你的email!

#------------------------
# latex config
#------------------------
# choose true to use latex by mathjax or katex
# warning: latex rendering will put lots of loading burden on page loading
latex:
  enable: true
  engine: katex # mathjax | katex
  # for better rendering effect, when you choose mathjax, you can use it directly but you will lose some effect
  # so you can use hexo-renderer-kramed
  # when you choose katex, you must use hexo-renderer-markdown-it-plus or other render engine
  global: false
  # when you choose false, you can use latex by `latex: true` in post front-matter

#------------------------
# lazyload config
#------------------------
lazyload:
  enable: true
  loadingImg:

#------------------------
# plugins config
#------------------------
lightbox:
  enable: true
# If your hexo version is below 5.0.0, please upgrade first to use this config
# we support eight highlight themes, you can go to prism website (https://prismjs.com) for more information
# theme: default | coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
prism:
  theme: default
  darkTheme: tomorrow
# show the number of words in posts
wordcount:
  enable: true
# Analytics config
analytics:
  enable: true
  type: google # google
  google:
    id: G-9YJQY0GQ6N # you can see more information in https://analytics.google.com/
# Doc：https://artitalk.js.org/
artitalk:
  enable: false
  appId: 
  appKey: 
#------------------------
# minify config
# css minify uses autoprefixer and clean-css
# javascript minify uses uglify-es
# html minify uses html-minifier
#------------------------
minify:
  enable: false
  css: true
  js: true
  html: true
#------------------------
# theme design config
#------------------------
# the config of theme colors and styles
# you can modify these presets to design different styles
color:
  text-color: "#3c4858"
  text-strong-color: "#2f3d4e"
  text-light-color: "#60656a"
  divider-color: "#e6e8ee"
  title-color: "#475b6d"
  link-color: "#3273dc"
  link-hover-color: "#6596e5"
  info-text-color: "#60656a"
  widget-background-color: "#fff"
  body-background-color: "#f2f5f8"
  border-color: "#e1e4e9"
  pre-color: "#2d2d2d"
  code-color: "#50687c"
  code-background-color: "#e9eaf0"

font:
  font-size: 15px # global font-size
  font-family: '-apple-system,BlinkMacSystemFont,"Segoe UI","Helvetica Neue","PingFang SC","Microsoft YaHei",sans-serif' # global font-family

#------------------------
# cdn config
#------------------------
cdn:
  mathjax: //cdn.jsdelivr.net/npm/mathjax@3.0.5/es5/tex-svg.js
  katex: //cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css
  gitalk:
    css: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
    js: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js
  valine: //unpkg.com/valine/dist/Valine.min.js
  livere: //cdn-city.livere.com/js/embed.dist.js
  waline: 
    js: //unpkg.com/@waline/client@v2/dist/waline.js
    css: //unpkg.com/@waline/client@v2/dist/waline.css
  baguetteBox: /js/lib/lightbox
  lozad: /js/lib/lozad.min.js
  prism: /js/lib/prism/
  busuanzi: /js/lib/busuanzi.min.js
  artitalk: https://cdn.jsdelivr.net/npm/artitalk
  md5: /js/lib/md5.min.js
